/mavros/distance_sensor:
  ros__parameters:
    config: "rangefinder_down:\n  id: 0\n  frame_id: lidar_link\n  orientation: PITCH_270\n  field_of_view: 0.1\n  send_tf: false\n  sensor_position: {x: 0.0, y: 0.0, z: -0.1}\n"
