[General]
TcpServerPort = 5760
ReportStats = false
MavlinkDialect = ardupilotmega

[UartEndpoint PX4]
Device = /dev/ttyACM0
Baud = 921600

[UdpEndpoint QGC]
Mode = Normal
Address =    10.56.178.143
Port = 14550

[UdpEndpoint Script]
Mode = Normal
Address = 127.0.0.1
Port = 14540
