/**:
  ros__parameters:
    info_topic: "/camera/camera/color/camera_info"
    img_base_topic: "/camera/camera/color/image_raw"
    img_transport: "raw"
    
    num_markers: 1
    circle_diameter: 0.41
    
    identify: False
    id_bits: 3
    id_samples: 360
    hamming_dist: 1

    draw_coords: True
    draw_segments: True
    use_gui: True

    # use -1 to disable individual size checks
    min_size: 200
    max_size: 60000
    min_size_inner: 30
    min_size_outer: 30
    
    coords_method: 0  # 0 for camera centric coordinates
    calib_file: ""
    calib_dist_x: 1.0
    calib_dist_y: 1.0

    initial_circularity_tolerance: 100.0
    final_circularity_tolerance: 2.0
    area_ratio_tolerance: 40.0
    center_distance_tolerance_ratio: 10.0
    center_distance_tolerance_abs: 5.0
